from pathlib import Path


APP_NAME = "BoardBudget"
DEFAULT_HOURS_PER_DAY = 8.0
DEFAULT_WORKING_DAYS = ("MON", "TUE", "WED", "THU", "FRI")
DEFAULT_MAX_CALENDAR_DAYS = 730

ROOT_DIR = Path(__file__).resolve().parent.parent
BOARDS_DIR = ROOT_DIR / "boards"
EXPORTS_DIR = ROOT_DIR / "exports"

BOARD_SHEET = "01_Board"
PEOPLE_SHEET = "02_People"
ACTIVITIES_SHEET = "03_Activities"
ASSIGNMENTS_SHEET = "04_Assignments"
CALENDAR_SHEET = "05_Calendar"
DASHBOARD_SHEET = "06_Dashboard"
WARNINGS_SHEET = "07_Warnings"
ACTIVITY_ECONOMICS_SHEET = "08_Activity_Economics"

INPUT_SHEETS = (BOARD_SHEET, PEOPLE_SHEET, ACTIVITIES_SHEET, ASSIGNMENTS_SHEET)
GENERATED_SHEETS = (CALENDAR_SHEET, DASHBOARD_SHEET, WARNINGS_SHEET, ACTIVITY_ECONOMICS_SHEET)
ALL_SHEETS = INPUT_SHEETS + GENERATED_SHEETS

STATUS_PLANNED = "PLANNED"
STATUS_DONE = "DONE"
STATUS_CANCELLED = "CANCELLED"
ALLOWED_STATUSES = (STATUS_PLANNED, STATUS_DONE, STATUS_CANCELLED)

WEEKDAY_CODES = {
    "MON": 0,
    "TUE": 1,
    "WED": 2,
    "THU": 3,
    "FRI": 4,
    "SAT": 5,
    "SUN": 6,
}
